from . import afp
from . import isapre
from . import parametros_uf
from . import parametros_utm
from . import parametros_ingreso_minimo
from . import parametros_tabla_impuestos
from . import parametros_topes
from . import conf_ausencia_tipo
from . import conf_concepto
from . import conf_sobretiempo_tipo
from . import mov_ausencia
from . import mov_haber_descuento
from . import mov_sobretiempo
